FROM python:3.10

RUN apt-get update -y

RUN mkdir -p /src /log

COPY src/ /src/
COPY requirements.txt .

RUN pip install -r requirements.txt

RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

WORKDIR /src
ENTRYPOINT ["python", "app.py"]

CMD ["stg"]