FROM python:3.10

ARG SERVICE_FOLDER_NAME=stg_service

RUN apt-get update -y

RUN mkdir -p /src/lib /src/${SERVICE_FOLDER_NAME} /log

COPY src/app.py /src/
COPY src/${SERVICE_FOLDER_NAME} /src/${SERVICE_FOLDER_NAME}/
COPY src/lib/ /src/lib/
COPY requirements.txt .

RUN pip install -r requirements.txt

RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

WORKDIR /src
ENTRYPOINT ["python", "app.py"]

CMD ["stg"]