version: "3.9"

services:
  stg_service:
    build:
      context: .
      args:
        SERVICE_TYPE: stg
      dockerfile: dockerfile
      network: host
    image: stg_service:local
    container_name: stg_service_container
    env_file: env_file
    environment:
      FLASK_APP: stg_service
    network_mode: "bridge"
    ports:
      - "5012:5000"
    restart: unless-stopped

  dds_service:
    build:
      context: .
      args:
        SERVICE_TYPE: dds
      dockerfile: dockerfile
      network: host
    image: dds_service:local
    container_name: dds_service_container
    env_file: env_file
    environment:
      FLASK_APP: dds_service
    network_mode: "bridge"
    ports:
      - "5013:5000"
    restart: unless-stopped

  cdm_service:
    build:
      context: .
      args:
        SERVICE_TYPE: cdm
      dockerfile: dockerfile
      network: host
    image: cdm_service:local
    container_name: cdm_service_container
    env_file: env_file
    environment:
      FLASK_APP: cdm_service
    network_mode: "bridge"
    ports:
      - "5014:5000"
    restart: unless-stopped
