apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
    tier: {{ .Values.tier }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
      tier: {{ .Values.tier }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
        tier: {{ .Values.tier }}
    spec:
      containers:
        - name: {{ .Values.nameOverride }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.nameOverride }}-secret    
          resources:
            {{- toYaml .Values.resources | nindent 12 }}