apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-secret
  labels:
    app: {{ .Values.nameOverride }}
    tier: {{ .Values.tier }}
{{- with .Values.config }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}